server:
  port: 8101
spring:
  application:
    name: power-socket
  rabbitmq:
    host: 118.24.38.46
    port: 5672
    username: husen
    password: 521428
    virtual-host: /
#   开启发送确认
    publisher-confirms: true
#   开启发送失败退回
    publisher-returns: true
    listener:
      direct:
        retry:
          enabled: true
#       开启ACK
        acknowledge-mode: manual
      simple:
        retry:
          enabled: true
        acknowledge-mode: manual
#       消费者的最小数量
        concurrency: 10
#       消费者的最大数量
        max-concurrency: 20
#       在单个请求中处理的消息个数，他应该大于等于事务数量
        prefetch: 5
#       启动时自动启动容器
        auto-startup: true
#       投递失败时是否重新排队
        default-requeue-rejected: true
    template:
#     超时时间
      reply-timeout: 10000
#     设置为true的时候RabbitTemplate(生产端)能够实现重试
      retry:
        enabled: true
#       第一次与第二次发布消息的间隔
        initial-interval: 1000
#       尝试发布消息的最大数量
        max-attempts: 3
#       尝试发布消息的最大时间间隔
        max-interval: 10000
#       上一次尝试时间间隔的乘数
        multiplier: 1.0
app:
  id: Power
apollo:
  meta: http://192.168.247.135:8080
  bootstrap:
    enabled: true
    namespaces: application
    eagerLoad:
      enabled: true
dubbo:
  application:
    name: power-socket
  registry:
    address: zookeeper://118.24.38.46:2181