server:
  port: 8101
spring:
  application:
    name: power-socket
app:
  id: Power
apollo:
  meta: http://192.168.247.135:8080
dubbo:
  application:
    name: power-socket
  registry:
    address: zookeeper://118.24.38.46:2181